<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fa81fbbd-6fd8-4f03-994c-056ad20827c7</testSuiteGuid>
   <testCaseLink>
      <guid>9824f78a-2f8c-41a6-96e7-96920bf09731</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_page/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ff2cdb1f-d2e3-4d36-8504-b210cc52d60a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ff2cdb1f-d2e3-4d36-8504-b210cc52d60a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>94dddce2-14d7-494b-bc71-8acdb3b80d1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9049136-87b9-4950-a055-d5127a243ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff2cdb1f-d2e3-4d36-8504-b210cc52d60a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>6d9bf944-a6cd-401e-8bd4-60748a7e8902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2769f99-8695-4d50-9380-eaa19a4253d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81076970-fde6-4cab-81b4-1cc7ad6a1102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d459b412-53ed-4499-a050-e96f832d1302</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48997d51-cf05-472c-b7a6-3bc5b6eeb07e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cf4b23b-4b2d-43ea-a922-40901a8a4696</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1a8eaac-348f-4b7d-8152-6bc8b189fdef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e2f8e0c-9353-4dd5-9ee7-9fdd7a69fca0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
